name: Build .NET project

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - name: Wii_1.1
            flags: "#MWCC_WII_1_1#MWCC_WII_1_0#MWCC_GC_3_0#MWCC_GC_1_3_2"
          - name: Wii_1.0
            flags: "#MWCC_WII_1_0#MWCC_GC_3_0#MWCC_GC_1_3_2"
          - name: GC_3.0
            flags: "#MWCC_GC_3_0#MWCC_GC_1_3_2"
          - name: GC_2.7
            flags: "#MWCC_GC_1_3_2"
          - name: GC_1.0
            flags: ""

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: dotnet publish -p:DebugType=None -p:DebugSymbols=false -p:FeatureFlags="${{ matrix.flags }}"
    - name: Package
      run: |
        cd MwccInspectorUI/bin/Release/net9.0-windows7.0/
        Rename-Item -Path publish -NewName MwccInspector
    - name: Publish
      uses: actions/upload-artifact@v4.6.2
      with:
        name: MwccInspector-${{ matrix.name }}
        path: MwccInspectorUI/bin/Release/net9.0-windows7.0/MwccInspector/
